# Question 1

fruit_1 = input("Enter the name of the first fruit: ")
fruit_2 = input("Enter the name of the second fruit: ")
fruit_3 = input("Enter the name of the third fruit: ")
fruit_4 = input("Enter the name of the fourth fruit: ")
fruit_5 = input("Enter the name of the fifth fruit: ")
fruit_6 = input("Enter the name of the sixth fruit: ")
fruit_7 = input("Enter the name of the seventh fruit: ")

fruit_list = [fruit_1, fruit_2, fruit_3, fruit_4, fruit_5, fruit_6, fruit_7]

print(fruit_list)