programming_languages = {}

name = input("Enter your name: ")
lang = input("Enter your favorite programming language: ")

programming_languages[name] = lang

name = input("Enter your name: ")
lang = input("Enter your favorite programming language: ")

programming_languages[name] = lang

name = input("Enter your name: ")
lang = input("Enter your favorite programming language: ")

programming_languages[name] = lang

name = input("Enter your name: ")
lang = input("Enter your favorite programming language: ")

programming_languages.update({name: lang})

print(programming_languages)